create table fornecedor (
	cod_fornecedor INT PRIMARY KEY,
	nm_fornecedor VARCHAR(200),
	prod_fornecido VARCHAR(100)
);
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (1, 'Manhattan Associates, Inc.', 'Pião');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (2, 'SLM Corporation', 'Pé de Lata');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (3, 'CSG Systems International, Inc.', 'Pequeno Engenheiro');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (4, 'Virtus Investment Partners, Inc.', 'Tamagotchi');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (5, 'Glaukos Corporation', 'Ioiô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (6, 'Active Alts Contrarian ETF', 'Pipa');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (7, 'Taylor Devices, Inc.', 'Soldadinho de Plástico');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (8, 'Lazard World Dividend & Income Fund, Inc.', 'Pé de Lata');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (9, 'ESCO Technologies Inc.', 'Pipa');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (10, 'Inogen, Inc', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (11, 'NASDAQ TEST STOCK', 'Tamagotchi');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (12, 'W&T Offshore, Inc.', 'Pião');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (13, 'Potbelly Corporation', 'Carrinho de rolimã');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (14, 'Ctrip.com International, Ltd.', 'Bambolê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (15, 'German American Bancorp, Inc.', 'Boneco MAX Steel');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (16, 'United States Lime & Minerals, Inc.', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (17, 'RPC, Inc.', 'Tamagotchi');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (18, 'Eyegate Pharmaceuticals, Inc.', 'Tamagotchi');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (19, 'Hancock Holding Company', 'Ioiô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (20, 'Vornado Realty Trust', 'Bat Beg_Bate bate');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (21, 'Franklin Electric Co., Inc.', 'Bilboquê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (22, 'Endo International plc', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (23, 'CalAtlantic Group, Inc.', 'Triciculo Bandeirante');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (24, 'AlphaMark Actively Managed Small Cap ETF', 'Diabolô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (25, 'Central Federal Corporation', 'Boneco MAX Steel');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (26, 'Magellan Midstream Partners L.P.', 'Ioiô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (27, 'Pulse Biosciences, Inc', 'Pipa');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (28, 'FIRST REPUBLIC BANK', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (29, 'Triangle Capital Corporation', 'Boneca Barbie');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (30, 'PROS Holdings, Inc.', 'Carrinho de rolimã');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (31, 'Morgan Stanley China A Share Fund Inc.', 'Pega Peixes');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (32, 'Savara, Inc.', 'Pega Varetas');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (33, 'Dave & Buster''s Entertainment, Inc.', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (34, 'Axalta Coating Systems Ltd.', 'Soldadinho de Plástico');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (35, 'MediWound Ltd.', 'Mola Maluca_Molas colorida');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (36, 'Nuveen New York Municipal Value Fund, Inc.', 'Tazos');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (37, 'GenVec, Inc.', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (38, 'Socket Mobile, Inc.', 'Ioiô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (39, 'Armstrong Flooring, Inc.', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (40, 'Mallinckrodt plc', 'Soldadinho de Plástico');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (41, 'Albireo Pharma, Inc.', 'Pega Peixes');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (42, 'Western Asset/Claymore U.S Treasury Inflation Prot Secs Fd 2', 'Carrinho de rolimã');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (43, 'PIMCO California Municipal Income Fund', 'Homem Aranha');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (44, 'Polar Power, Inc.', 'Pião');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (45, 'LeMaitre Vascular, Inc.', 'Ioiô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (46, 'VelocityShares 3x Long Silver ETN', 'Diabolô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (47, 'China Xiniya Fashion Limited', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (48, 'HomeTrust Bancshares, Inc.', 'Diabolô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (49, 'Stanley Black & Decker, Inc.', 'Bambolê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (50, 'Nuveen Municipal High Income Opportunity Fund', 'Boneca Barbie');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (51, 'KKR & Co. L.P.', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (52, 'Conifer Holdings, Inc.', 'Pega Varetas');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (53, 'Nuveen Select Maturities Municipal Fund', 'Bilboquê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (54, 'Meridian Bancorp, Inc.', 'Genius');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (55, 'Citigroup Inc.', 'Pé de Lata');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (56, 'The Gabelli Healthcare & Wellness Trust', 'Bat Beg_Bate bate');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (57, 'PowerShares Global Gold & Precious Metals Portfolio', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (58, 'Avis Budget Group, Inc.', 'Cata-Vento');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (59, 'Full House Resorts, Inc.', 'Triciculo Bandeirante');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (60, 'Arc Logistic Partners LP', 'Pião');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (61, 'Oxbridge Re Holdings Limited', 'Tazos');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (62, 'Tempur Sealy International, Inc.', 'Futebol de Botão');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (63, 'UMB Financial Corporation', 'Tamagotchi');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (64, 'Woori Bank', 'Futebol de Botão');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (65, 'Athersys, Inc.', 'Bambolê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (66, 'Aaron''s,  Inc.', 'Pogobol');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (67, 'FalconStor Software, Inc.', 'Soldadinho de Plástico');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (68, 'Western Asset Global Corporate Defined Opportunity Fund Inc.', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (69, 'Comerica Incorporated', 'Bilboquê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (70, 'BankFinancial Corporation', 'Pião');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (71, 'Spartan Motors, Inc.', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (72, 'FCB Financial Holdings, Inc.', 'Tamagotchi');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (73, 'Forterra, Inc.', 'Bilboquê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (74, 'Yatra Online, Inc.', 'Tazos');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (75, 'Mednax, Inc', 'Pogobol');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (76, 'Nuveen Tax-Advantaged Total Return Strategy Fund', 'Pogobol');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (77, 'Dominion Energy, Inc.', 'Futebol de Botão');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (78, 'TCF Financial Corporation', 'Cata-Vento');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (79, 'Elkhorn Commodity Rotation Strategy ETF', 'Pega Peixes');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (80, 'SuperCom, Ltd.', 'Cata-Vento');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (81, 'SeaWorld Entertainment, Inc.', 'Bola de Gude');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (82, 'Customers Bancorp, Inc', 'Forte Apache');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (83, 'STORE Capital Corporation', 'Pé de Lata');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (84, 'EVINE Live Inc.', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (85, 'China Green Agriculture, Inc.', 'Tazos');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (86, 'Nokia Corporation', 'Furby');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (87, 'AC Immune SA', 'Boneco MAX Steel');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (88, 'United Bancshares, Inc.', 'Bambolê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (89, 'Interactive Brokers Group, Inc.', 'Furby');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (90, 'Macro Bank Inc.', 'Pirocóptero');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (91, 'Silver Run Acquisition Corporation II', 'Pé de Lata');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (92, 'Lincoln Educational Services Corporation', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (93, 'Forum Merger Corporation', 'Carrinho de rolimã');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (94, 'Ryder System, Inc.', 'Pogobol');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (95, 'Source Capital, Inc.', 'Carrinho de rolimã');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (96, 'ResMed Inc.', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (97, 'Live Oak Bancshares, Inc.', 'Triciculo Bandeirante');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (98, 'TravelCenters of America LLC', 'Bat Beg_Bate bate');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (99, 'Rosehill Resources Inc.', 'Tamagotchi');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (100, 'NMI Holdings Inc', 'Aquaplay');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (101, 'Eiger BioPharmaceuticals, Inc.', 'Pião');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (102, 'Bazaarvoice, Inc.', 'Aquaplay');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (103, 'Avista Healthcare Public Acquisition Corp.', 'Bambolê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (104, 'Leidos Holdings, Inc.', 'Boneco MAX Steel');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (105, 'ImmuCell Corporation', 'Homem Aranha');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (106, 'First Trust New Opportunities MLP & Energy Fund', 'Aquaplay');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (107, 'SteadyMed Ltd.', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (108, 'Axis Capital Holdings Limited', 'Boneca Barbie');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (109, 'Medpace Holdings, Inc.', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (110, 'Aimmune Therapeutics, Inc.', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (111, 'Lennox International, Inc.', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (112, 'Active Alts Contrarian ETF', 'Homem Aranha');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (113, 'Tortoise Energy Infrastructure Corporation', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (114, 'BioSpecifics Technologies Corp', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (115, 'MS Income Securities, Inc.', 'Peteca');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (116, 'Smart Sand, Inc.', 'Ioiô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (117, 'JD.com, Inc.', 'Bambolê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (118, 'Pacific Biosciences of California, Inc.', 'Bat Beg_Bate bate');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (119, 'TOP Ships Inc.', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (120, 'American Homes 4 Rent', 'Bola de Gude');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (121, 'PartnerRe Ltd.', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (122, 'Las Vegas Sands Corp.', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (123, 'Oasmia Pharmaceutical AB', 'Boneco MAX Steel');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (124, 'West Marine, Inc.', 'Bat Beg_Bate bate');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (125, 'Watsco, Inc.', 'Diabolô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (126, 'Franklin Covey Company', 'Forte Apache');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (127, 'TriState Capital Holdings, Inc.', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (128, 'Cardiovascular Systems, Inc.', 'Pega Peixes');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (129, 'Sonoma Pharmaceuticals, Inc.', 'Pogobol');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (130, 'Enterprise Bancorp Inc', 'Aquaplay');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (131, 'Asta Funding, Inc.', 'Peteca');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (132, 'Ameresco, Inc.', 'Carrinho de rolimã');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (133, 'Nuveen Preferred Income Opportunites Fund', 'Bat Beg_Bate bate');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (134, 'Associated Banc-Corp', 'Pipa');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (135, 'SuperCom, Ltd.', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (136, 'Pennsylvania Real Estate Investment Trust', 'Pogobol');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (137, 'Stericycle, Inc.', 'Pião');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (138, 'Cartesian, Inc.', 'Triciculo Bandeirante');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (139, 'Tarena International, Inc.', 'Peteca');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (140, 'iShares S&P India Nifty 50 Index Fund', 'Diabolô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (141, 'Parker Drilling Company', 'Pé de Lata');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (142, 'Casella Waste Systems, Inc.', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (143, 'Scholastic Corporation', 'Pega Peixes');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (144, 'Barington/Hilco Acquisition Corp.', 'Diabolô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (145, 'Ocular Therapeutix, Inc.', 'Bat Beg_Bate bate');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (146, 'Sasol Ltd.', 'Dominó');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (147, 'Poage Bankshares, Inc.', 'Mola Maluca_Molas colorida');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (148, 'Turtle Beach Corporation', 'Carrinho de rolimã');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (149, 'Western Refining Logistics, LP', 'Homem Aranha');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (150, 'PDL BioPharma, Inc.', 'Diabolô');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (151, 'EQT GP Holdings, LP', 'Pega Varetas');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (152, 'GTx, Inc.', 'Soldadinho de Plástico');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (153, 'ScanSource, Inc.', 'Pequeno Engenheiro');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (154, 'Nymox Pharmaceutical Corporation', 'Pequeno Engenheiro');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (155, 'Cimarex Energy Co', 'Pião');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (156, 'National Retail Properties', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (157, 'First Trust Taiwan AlphaDEX Fund', 'Genius');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (158, 'Floor & Decor Holdings, Inc.', 'Boneco MAX Steel');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (159, 'Teekay Offshore Partners L.P.', 'Pega Peixes');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (160, 'Ubiquiti Networks, Inc.', 'Furby');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (161, 'Liberty Interactive Corporation', 'Boneca Barbie');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (162, 'FutureFuel Corp.', 'Dama');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (163, 'Seaspan Corporation', 'Tazos');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (164, 'National Health Investors, Inc.', 'Bilboquê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (165, 'Endurance International Group Holdings, Inc.', 'Carrinho de rolimã');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (166, 'American Financial Group, Inc.', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (167, 'Nuveen Select Tax Free Income Portfolio', 'Forte Apache');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (168, 'First Trust Rising Dividend Achievers ETF', 'Forte Apache');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (169, 'Blackrock Florida Municipal 2020 Term Trust', 'Tamagotchi');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (170, 'Clearfield, Inc.', 'Cata-Vento');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (171, 'MDU Resources Group, Inc.', 'Aquaplay');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (172, 'ESCO Technologies Inc.', 'Tamagotchi');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (173, 'Walgreens Boots Alliance, Inc.', 'Vai-Vem');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (174, 'Dupont Fabros Technology, Inc.', 'Bat Beg_Bate bate');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (175, 'Bojangles'', Inc.', 'Bilboquê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (176, 'Safe Bulkers, Inc', 'Peteca');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (177, 'Resonant Inc.', 'Genius');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (178, 'Virtus Total Return Fund Inc.', 'Bambolê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (179, 'Spark Energy, Inc.', 'Tazos');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (180, 'Sunstone Hotel Investors, Inc.', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (181, 'Brocade Communications Systems, Inc.', 'Mola Maluca_Molas colorida');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (182, 'NewMarket Corporation', 'Soldadinho de Plástico');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (183, 'American Software, Inc.', 'Carrinho de rolimã');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (184, 'Miragen Therapeutics, Inc.', 'Boneca Barbie');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (185, 'J P Morgan Chase & Co', 'Homem Aranha');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (186, 'Dynavax Technologies Corporation', 'Pequeno Engenheiro');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (187, 'Four Corners Property Trust, Inc.', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (188, 'Cumberland Pharmaceuticals Inc.', 'Peteca');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (189, 'ASB Bancorp, Inc.', 'Bilboquê');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (190, 'Merrill Lynch Depositor, Inc.', 'Soldadinho de Plástico');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (191, 'NetApp, Inc.', 'Bola de Gude');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (192, 'U.S. Bancorp', 'Pega Varetas');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (193, 'Kennedy-Wilson Holdings Inc.', 'Dama');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (194, 'Goldman Sachs BDC, Inc.', 'Soldadinho de Plástico');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (195, 'Qorvo, Inc.', 'Bola de Gude');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (196, 'Matlin & Partners Acquisition Corporation', 'Genius');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (197, 'Home Federal Bancorp, Inc. of Louisiana', 'Aquaplay');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (198, 'Albemarle Corporation', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (199, 'First Bancorp', 'Perna de Pau');
insert into fornecedor (cod_fornecedor, nm_fornecedor, prod_fornecido) values (200, 'Home Depot, Inc. (The)', 'Bilboquê');
