insert into produto (nm_produto, valor_produto, cod_tipo) values ('max steel', 30, 1);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('barbie 1 ', 50, 1);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('barbie 2 ', 60, 1);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('barbie 3 ', 20, 1);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('barbie 4 ', 30, 1);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Pepa pig ', 120, 1);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Funko pop Shrek ', 200, 1);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Bicicleta infantil tipo 1 ', 300, 2);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Bicicleta infantil tipo 2 ', 300, 2);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Patinete max steel ', 100, 2);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Patinete Barbie ', 120, 2);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Ursinho de pelucia Seu amigao ', 10, 3);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Cavalo de pelucia Sla ', 20, 3);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('alguma coisa de pelucia ', 4, 3);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('WAR ', 50, 4);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('UNO ', 40, 4);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Quebra cabeca 1000 pecas ', 70, 4);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Banco Imobiliario ', 90, 4);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Pote de maizena ', 3, 5);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Amoeba 1', 10, 5);
insert into produto (nm_produto, valor_produto, cod_tipo) values ('Amoeba 2', 10, 5);

